name: Surge Deployment
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install -g surge
      - run: surge ./ --token ${{ secrets.SURGE_TOKEN }}
